### ISSUE TITLE
"Community" in the site top bar does not highlight when current page

### ISSUE THREAD

**Issue by pradyunsg** [proevo/pythondotorg#1894] opened 2021-10-17 01:03 UTC
**Describe the bug**

Title says it all?

**To Reproduce**

1. Go to https://www.python.org/
2. Click on "Community" in the top bar.
3. Move mouse outside of the top bar.
4. Notice that "Python" is the currently-highlighted item in the top bar.

**Expected behavior**

This behaviour can be contrasted against how the PSF item in the top bar behaves. It is highlighted, when on a page within it's subtree.

**Screenshots**

(incorrect)
<img width="1206" alt="Screenshot 2021-10-17 at 02 01 56" src="https://user-images.githubusercontent.com/3275593/137606102-0643d6b6-9c71-4580-ae21-c020e377c0b7.png">

(correct)
<img width="1206" alt="Screenshot 2021-10-17 at 02 01 49" src="https://user-images.githubusercontent.com/3275593/137606104-1f3897a1-6e67-431d-9f10-ef3cf634fe24.png">

**Desktop**
 - OS: MacOS
 - Browser: Firefox
 - Version: 93.0

**Additional context**

It seems like we're missing two things:

- The CSS selector for `.community` in https://github.com/python/pythondotorg/blob/7556542b58d9c90717757c9fa997637752d6dd85/static/sass/style.scss#L380-L390.
- Whatever the site CMS information is to get the `jobs` class on body, in the staging environment.

**Comment by hugovk** [comment] 2024-09-07 11:31
Thanks, closing as a duplicate of https://github.com/python/pythondotorg/issues/1433. I'll post this info over there.

**Closed as not planned by hugovk** 2024-09-07 11:31 UTC
