### ISSUE TITLE
Donor Honor Roll is empty

### ISSUE THREAD

**Issue by Kwpolska** [proevo/pythondotorg#2435] opened 2024-04-15 20:55 UTC
**Describe the bug**
The list of donors is missing.

**To Reproduce**
Go to https://www.python.org/psf/donations/#donors and observe the void.

**Expected behavior**
A list of donors.

**Screenshots**

![image](https://github.com/python/pythondotorg/assets/327323/39ac70a0-4a98-445d-8b32-750e3814727a)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 124

**Comment by bslatkin** [comment] 2024-04-17 16:01
Looks like the last time it was working was back in December 2023. Using the Wayback machine, this was the most recent snapshot that I could see that was still working:

https://web.archive.org/web/20231203152613/https://www.python.org/psf/donations/

**Comment by willingc** [comment] 2024-04-17 16:29
Perhaps displaying as a wordcloud (maybe in the shape of the Python logo) would be a fun way to recognize donors.

**Comment by indepndnt** [comment] 2024-04-17 19:06
The honor roll is populated by a separate project via an API call to python.org. I upgraded to sqlalchemy 2.0 and broke a property on the donation database table that provided the age of the donations, and none of them qualified to be included. This is fixed now, and once any relevant caches expire you should see the current list on the web site.

**Comment by Mariatta** [comment] 2024-04-17 19:26
Thanks @indepndnt! Confirmed that the list is showing up now. Thanks for reporting, @Kwpolska.

**Closed as completed by Mariatta** 2024-04-17 19:26 UTC

**Comment by bslatkin** [comment] 2024-04-17 19:40
@indepndnt Thanks for fixing it! I'm curious if the query is still generating the same data as before? The table has changed so much from the December 2023 version (see wayback link in my comment above).

**Comment by indepndnt** [comment] 2024-04-17 22:39
@bslatkin The basis is the same. The algorithm used includes the number of donations, age of donations, and amounts to rank them so there tends to be a lot of fluctuation in the order, especially in the lead up to PyCon US.

**Comment by indepndnt** [comment] 2024-04-17 22:40
@willingc That does sound like a fun idea, and thanks to the magic of `import wordcloud`, I've implemented it.

**Comment by willingc** [comment] 2024-04-17 22:41
I just saw @indepndnt! It made my day to see it.

**Comment by Mariatta** [comment] 2024-04-17 22:47
It looks so cool!! Thank you @indepndnt !
