### ISSUE TITLE
Please provide dark mode to official website.

### ISSUE THREAD

**Issue by vishnubhandarge** [proevo/pythondotorg#2269] opened 2023-04-24 16:08 UTC

**Comment by vishnubhandarge** [comment] 2023-04-24 16:10
Please provide dark mode to python official site.

**Comment by hugovk** [comment] 2023-05-14 09:11
Duplicate of https://github.com/python/pythondotorg/issues/1725

**Comment by eamanu** [comment] 2023-05-14 13:15
Yes, seems that this issue can be close.

**Closed as completed** 2023-05-14 15:25 UTC
