### ISSUE TITLE
Broken Volunteer link at https://www.python.org/psf-landing/

### ISSUE THREAD

**Issue by EricRa** [proevo/pythondotorg#2470] opened 2024-06-24 02:50 UTC
**Describe the bug**
At https://www.python.org/psf-landing/ or from any python.org/psf page, the link for Volunteer > Volunteer for the PSF returns a 404.  

Specifically, the link goes to: https://www.python.org/psf/volunteer/psf (404)
I believe that it should instead point to: https://www.python.org/psf/volunteer/

**To Reproduce**
1. Go to https://www.python.org/psf-landing/
2. Hover/click Volunteer
3. Click Volunteer for the PSF

**Expected behavior**
Expected to reach the volunteer page actually located at https://www.python.org/psf/volunteer/.

**Screenshots**

**Desktop (please complete the following information):**
Windows, Firefox, latest version as of 6/23/24

**Comment by hugovk** [comment] 2024-06-24 04:49
Thanks for the report, this is a duplicate of https://github.com/python/pythondotorg/issues/2250.

**Comment by JacobCoffee** [comment] 2024-07-09 16:39
Thanks! As Hugo mentioned its a dupe, so I'm closing in favor of the first-reported one :)

**Closed as completed by JacobCoffee** 2024-07-09 16:39 UTC
