### ISSUE TITLE
Hover line of community button on the header doesn't work on the site.

### ISSUE THREAD

**Issue by Jalithc** [proevo/pythondotorg#2444] opened 2024-05-06 06:11 UTC
**The hover line of the community button on header doesn't work on the site.**
The hover line effect intended for the community button on the website's header is not functioning as expected. Upon hovering over the community button, a visual indicator in the form of a line should appear, providing feedback to users that the button is interactive. However, this hover line effect is not being displayed. 

**To Reproduce**
1. Go to 'https://www.python.org/community/'
2. Click on 'community button on header section'

**Expected behavior**
when you hover over a button or a link on a website, there's a visual change to indicate that it's clickable or active. This might include a change in color, underlining, or the appearance of a border or line under the button.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [Chrome]
 - Version [new]

**Comment by hugovk** [comment] 2024-09-07 11:29
Thanks for the report, this is a duplicate of https://github.com/python/pythondotorg/issues/1433 and https://github.com/python/pythondotorg/issues/1894.

**Closed as not planned by hugovk** 2024-09-07 11:29 UTC
