### ISSUE TITLE
Issue with > and < not completely working.

### ISSUE THREAD

**Issue by Shikamaru5** [proevo/pythondotorg#2072] opened 2022-07-04 20:01 UTC
So I could very well be wrong about this or doing this incorrectly but it doesn't seem to be doing the basic function I'm asking it to do. I don't truly care about the actual program it's just, in my real program I noticed that the less than sign (<) isn't doing the function you'd think it capable of. Testing out the greater than sign (>) also was a little wonky. When I try to run this program it says true for the first one and the last one, but the other three lines aren't working. It doesn't seem all that complicated so it should in my opinion work, does it maybe have something to do with how I've ordered the variables in each of the problems? I've also updated to the latest version of python that came out yesterday.

     import math

     def math():
	     x = 1
	     y = 2

	     if x < y:
		   print('True')

	     if y < x:
		   print('True')

	     if 2 < 1:
		   print('True')

	     if x > y:
		   print('True')
           
         if 2 > 1:
		   print('True')

     math()

**Comment by Mariatta** [comment] 2022-07-04 20:54
I'm closing since this issue is not relevant to the repository. This repo is for issues related to the Python.org website, not for general programming questions about Python.

I looked at your code snippet, and it seems to me that the code works as intended.

**Closed as not planned** 2022-07-04 20:54 UTC

**Comment by Shikamaru5** [comment] 2022-07-05 17:42
Ya apologies it does work, I was just exhausted after programming all day, didn't have the brain power to solve problems anymore but unfortunately was trying to do so anyway, it's just how it goes I guess. Did figure at the time though if it were a real issue that it would've been a relevant bug for python to fix. Thanks for your patience will the silly issue.
