### ISSUE TITLE
Dark theme not working properly

### ISSUE THREAD

**Issue by ignacioeg23** [proevo/pythondotorg#2371] opened 2024-02-21 11:24 UTC
**Describe the bug**
Dark theme in firefox 122.0.1 (64-bit), the snap version for ubuntu it is not working properly.
The boxes where the code is contained is white (or a very light color) and part of the text is white (or a very light color) too

**To Reproduce**
1. open any page with auoto or dark theme

**Expected behavior**
The back of the code box should be a dark color

**Screenshots**
![Screenshot from 2024-02-21 06-17-32](https://github.com/python/pythondotorg/assets/78541088/73496f40-a7ef-4a8b-a8a5-e37f93a9c3f4)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Browser Firefox
 - Version 122.0.1 (64-bit), the snap version for ubuntu

**Comment by hugovk** [comment] 2024-02-21 11:28
Thanks for the report.

This is a duplicate of https://github.com/python/cpython/issues/115349 which has been fixed, and will be deployed when the next 3.8 and 3.9 releases go out, which I think should be soon.

In the meantime, you can visit the docs for 3.10 or later.

**Closed as completed** 2024-06-18 00:28 UTC
